### ISSUE TITLE
Unable to install CBP

### ISSUE THREAD

**Issue by lamatieregrise** [vdm-io/JCB-Packages#2]
Tried the usual import, able to get package,  input the key then blank, tried it with safari end up  getting a blank screen, with Chrome i get a lost connect. strange tried also downloading the zip got the same result.

Francois

**Comment by Llewellynvdm** [comment]
It is a big package so you should check that your php settings allow files above 25 MB to be uploaded.

I just tested it and it works as expected.

**Comment by Llewellynvdm** [comment]
Here is a little recording https://youtu.be/4-DnD5MEuy4 of the import done as a demonstration that it works.

**Comment by lamatieregrise** [comment]
I believe you, I even put the file on the server (unix) itself, raise to 64m everywhere and put 120 sec to insure no hanging but keep getting on chrome nobs.work is currently unable to handle this request.
HTTP ERROR 500 if you want can give you an access to the back end, so you might see something i dont, because all the other worked fine. just strange :-)

**Comment by Llewellynvdm** [comment]
Not that I think this should play a roll, but have you tried with Firefox?

**Comment by lamatieregrise** [comment]
Just tried it same think blank screen, i doubt it but, could it be because
i'm doing from a mac computer?

**Comment by lamatieregrise** [comment]
Join to try tonite on a pc its the only option remaining to visit even tried on a blank site

**Comment by Llewellynvdm** [comment]
The other option is for me to revert the package to not include the DB demo data.

**Comment by Llewellynvdm** [comment]
Try this package
[JCB_costBenefitProjectionPublic.zip](https://github.com/vdm-io/JCB-Packages/files/2028500/JCB_costBenefitProjectionPublic.zip)

**Comment by lamatieregrise** [comment]
Bang! it work like a charm. You have what version of mysql? here are the spec of my server, the one  i' m using the . most for JCB

Server: Localhost via UNIX socket
Server type: MariaDB
Server version: 10.1.33-MariaDB - MariaDB Server
nginx/1.11.10
Database client version: libmysql - mysqlnd 5.0.12
PHP version: 7.1.14

**Comment by lamatieregrise** [comment]
Only chrome  was not going blank, it was the only on that did at least givesme indication an error 500 lost connection warning, btw by the end of next week i should get less busy and get on the language project since the first iteration of what i was working will reach the first milestone thanks to JCB.

**Comment by Llewellynvdm** [comment]
Well it is a mySql dump file, and not MariaDB. Not sure how big difference there is.

I am on mysql 5.7.22-0ubuntu0.16.04.1

**Comment by Llewellynvdm** [comment]
Also think it could be due to the size of the dump file.

**Comment by lamatieregrise** [comment]
but i was able to install the umapped version this morning with its dump ... i'm not sure that was the problem

**Comment by Llewellynvdm** [comment]
When it is a Joomla component it uses the correct paths to move that kind of data, but when it is a JCB package it moves that huge amount of data via PHP, I really think it is a server limitation in some form or another. Not a limitation that is in error, just that the file size is pushing up against that limitation.

My local development environment is little bigger then normal, and I often forget not everyone has 20 GiB of memory that they can just use... So I will update the package to use less memory, so it can always work everywhere.
